Add toggle and coachmark
groupme/android-video-kit pull request #7
Opened 2021-02-17 20:36 UTC by ra0s

Added a toggle switch that can change trim length duration, or be used to send an extra property outside of the trimmer (using the switch state). Added the option to show a coachmark on the switch

2021-02-18 15:38 UTC, ra0s commented
Picture of what it looks like with the toggle and coachmark:
![image](https://user-images.githubusercontent.com/19509608/108380983-60be7780-71d5-11eb-9bc5-ef124bec2df1.png)

2021-02-18 21:46 UTC, mwdavis84 commented on videokit/build.gradle
> +    implementation 'com.github.TouchType:CornedBeef:-SNAPSHOT'
We try to bring in specific versions of third party dependencies

2021-02-18 21:46 UTC, mwdavis84 commented on build.gradle
> +            url "https://jitpack.io"
Is this for the coachmark framework? Is it not available on jcenter?

2021-02-18 21:46 UTC, mwdavis84 commented on videokit/src/main/java/com/android/gallery3d/app/CommonControllerOverlay.java
> +        mToggleSwitchView.layout(0, y - (int) (1.5 * mTimeBar.getPreferredHeight())  , w, y);
Extra spaces here

2021-02-18 21:46 UTC, mwdavis84 commented on videokit/src/main/java/com/android/gallery3d/app/CommonControllerOverlay.java
> +        mBackground.layout(0, y - (int) (1.5 * mTimeBar.getBarHeight()), w, y);
Why 1.5?

2021-02-18 21:46 UTC, mwdavis84 commented on videokit/src/main/java/com/android/gallery3d/app/TrimControllerOverlay.java
> +        mToggleSwitch.post(new Runnable() {
Can this runnable be done in Lambda syntax?

2021-02-18 22:18 UTC, ra0s commented on videokit/src/main/java/com/android/gallery3d/app/CommonControllerOverlay.java
> +        mBackground.layout(0, y - (int) (1.5 * mTimeBar.getBarHeight()), w, y);
Admittedly this is some layout-fu to help accommodate for increased size needed to show the background behind the toggle switch. Making it twice the size extends it much further than is needed, while not extending it at all does not show the background behind the switch

2021-02-18 22:20 UTC, ra0s commented on videokit/src/main/java/com/android/gallery3d/app/TrimControllerOverlay.java
> +        mToggleSwitch.post(new Runnable() {
I had no idea that was a thing but seems likely - will take a look at this

2021-02-20 00:38 UTC, bsiegel requested changes
Only thing I think we absolutely need to resolve here is that we can't rely on getting the coachmark library via jitpack. Aside from that, just a few improvements / suggestions.

2021-02-20 00:38 UTC, bsiegel commented on build.gradle
> +            url "https://jitpack.io"
It looks like it's not published anywhere. Jitpack just lets you point to a GitHub repo and consume the artifact manually. We should probably publish this artifact to an AzDevOps feed, with a version assigned, and consume it from there.

2021-02-20 00:38 UTC, bsiegel commented on videokit/build.gradle
> +    implementation 'com.github.TouchType:CornedBeef:-SNAPSHOT'
Right, see above.

2021-02-20 00:38 UTC, bsiegel commented on videokit/src/main/java/com/android/gallery3d/app/CommonControllerOverlay.java
> +        ColorStateList trackColor = ColorStateList.valueOf(getResources().getColor(R.color.white));
Micro-optimization: this can go inside the conditional to avoid being called at all on older versions.

2021-02-20 00:38 UTC, bsiegel commented on videokit/src/main/java/com/android/gallery3d/app/TrimControllerOverlay.java
> +        mToggleSwitch.post(new Runnable() {
Yep, any java type with a single abstract method can be written as `(arg list) -> expression` or (arg list) -> { body }`

2021-02-20 00:38 UTC, bsiegel commented on videokit/src/main/java/com/android/gallery3d/app/TrimVideo.java
> +                mController.mToggleSwitch.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
This can also be done with lambda syntax

2021-02-20 00:38 UTC, bsiegel commented on videokit/src/main/java/com/android/gallery3d/app/CommonControllerOverlay.java
> +        mBackground.layout(0, y - (int) (1.5 * mTimeBar.getBarHeight()), w, y);
Hmm, it would be nice if we could actually measure the height correctly. I am also suspicious of this magic. Also for my benefit could you briefly describe the difference between getPreferredHeight and getBarHeight?

2021-02-22 18:11 UTC, ra0s commented on videokit/src/main/java/com/android/gallery3d/app/CommonControllerOverlay.java
> +        mBackground.layout(0, y - (int) (1.5 * mTimeBar.getBarHeight()), w, y);
Will modify this to use a more specific height. getPreferredHeight -> the height of the bar including padding getBarHeight -> height of the bar without padding

2021-02-22 20:56 UTC, ra0s commented on videokit/src/main/java/com/android/gallery3d/app/TrimControllerOverlay.java
> +        mToggleSwitch.post(new Runnable() {
Changed to runnable in latest commit

2021-02-22 20:59 UTC, ra0s commented on videokit/src/main/java/com/android/gallery3d/app/TrimVideo.java
> +                mController.mToggleSwitch.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
Updated in latest commit

2021-02-23 23:10 UTC, bsiegel commented on build.gradle
> +            url "https://jitpack.io"
I built and published the CornedBeef library to our public artifact feed here: https://dev.azure.com/groupme/public/_packaging?_a=package&feed=oss&package=com.swiftkey%3Acornedbeef&protocolType=maven&version=2.0.5

You can connect to the feed by adding this repository block:

```gradle
maven {
    url 'https://pkgs.dev.azure.com/groupme/public/_packaging/oss/maven/v1'
}
```

and then specifying the dependency as:

```gradle
implementation 'com.swiftkey:cornedbeef:2.0.5'
```

2021-02-24 18:37 UTC, bsiegel approved these changes
:+1::sparkles:Ship It:sparkles::shipit:

**Note:** Please pull latest master and rebase this branch onto it before merging this pull request.

~~~shell
$ git checkout master
$ git pull origin master

$ git checkout -
$ git rebase master

$ git push -f
~~~

2021-02-24 18:58 UTC, merged